import { Toaster } from "sonner";
import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import { ReactQueryClientProvider } from "@/components/ReactQueryClientProvider";
import "./globals.css";
import { ReduxProvider } from "@/components/ReduxProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <ReduxProvider>
        <html lang="en">
          <body>
            <Navbar />
            <section className="px-20 py-5">{children}</section>
            <Toaster position="top-right" richColors />
          </body>
        </html>
      </ReduxProvider>
    </ReactQueryClientProvider>
  );
}
